AWSTemplateFormatVersion: "2010-09-09"

Description: Serets Manager for line-slideshow

Parameters:
  Env:
    Type: String

Resources:
  LineSlideshowSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub line-slideshow-sm-${Env}
      Description: !Sub Secrets Manager for line-slideshow-${Env}
      Tags:
        - Key: system
          Value: line-slideshow
      KmsKeyId: alias/aws/secretsmanager
