AWSTemplateFormatVersion: "2010-09-09"

Description: API Gateway for line-slideshow

Parameters:
  Env:
    Type: String
  LineSlideshowSqsArn:
    Type: String
  ApigwCallingSqsRoleArn:
    Type: String

Resources:
  LineSlideshowApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub line-slideshow-apigw-${Env}
      Description: !Sub API Gateway for line-slideshow-${Env}
      Tags:
        - Key: system
          Value: line-slideshow
      EndpointConfiguration:
        Types:
          - REGIONAL
      Body:
        swagger: "2.0"
        info:
          description: !Sub API Gateway for line-slideshow-${Env}
          version: "1.0.0"
          title: !Sub line-slideshow-apigw-${Env}
        host: "leojboio40.execute-api.ap-northeast-1.amazonaws.com"
        basePath: !Sub "/${Env}"
        schemes:
          - "https"
        paths:
          /:
            post:
              consumes:
                - "application/json"
              parameters:
                - name: "x-iine-signature"
                  in: "header"
                  required: true
                  type: "string"
              responses:
                "200":
                  description: "200 response"
                "403":
                  description: "200 response"
                "500":
                  description: "200 response"
              x-amazon-apigateway-integration:
                credentials: !Sub "arn:aws:iam::935428647279:role/apigw-calling-sqs-role-${Env}"
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:sqs:path/${AWS::AccountId}/line-slideshow-sqs-${Env}"
                responses:
                  default:
                    statusCode: "200"
                requestParameters:
                  integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
                requestTemplates:
                  application/json: "Action=SendMessage&MessageBody=$util.urlEncode($input.body)"
                passthroughBehavior: "when_no_templates"
                type: "aws"
  LineSlideshowApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - LineSlideshowApiGateway
    Properties:
      RestApiId: !Ref LineSlideshowApiGateway
      StageName: !Ref Env
