AWSTemplateFormatVersion: "2010-09-09"

Description: API Gateway for line-slideshow

Parameters:
  Env:
    Type: String
  LineSlideshowSqsArn:
    Type: String
  ApigwCallingSqsRoleArn:
    Type: String

Resources:
  LineSlideshowApiGatewayCFn:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./apigw.yaml
      Parameters:
        Env: !Ref Env
        LineSlideshowSqsArn: !Ref LineSlideshowSqsArn
        ApigwCallingSqsRoleArn: !Ref ApigwCallingSqsRoleArn

  LineSlideshowApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Sub ${Env}
      RestApiId: !GetAtt LineSlideshowApiGatewayCFn.Outputs.LineSlideshowApiGatewayId
      DeploymentId: !GetAtt LineSlideshowApiGatewayCFn.Outputs.LineSlideshowApiGatewayDeploymentId
      Variables:
        Env: !Ref Env
      MethodSettings:
        - ResourcePath: /
          HttpMethod: POST
          MetricsEnabled: true
          DataTraceEnabled: true
          LoggingLevel: INFO
          CachingEnabled: false
