AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: lambda for MakeSlideshow

Globals:
  Function:
    Timeout: 30

Parameters:
  Env:
    Type: String
  MakeSlideshowRoleArn:
    Type: String

Conditions:
  IsDev: !Equals [!Ref Env, dev]

Resources:
  MakeSlideshowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub make-slideshow-${Env}
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 600
      MemorySize: !If [IsDev, 2048, 5000]
      Architectures:
        - x86_64
      Tags:
        system: line-slideshow
      Environment:
        Variables:
          ENV: !Ref Env
          TZ: Asia/Tokyo
      Role: !Ref MakeSlideshowRoleArn
