AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: lambda for MakeSlideshow

Globals:
  Function:
    Timeout: 30

Parameters:
  Env:
    Type: String

Resources:
  MakeSlideshowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub make-slideshow-${Env}
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 600
      MemorySize: 2048
      # Layers:
      # - arn:aws:lambda:ap-northeast-1:935428647279:layer:ffmpeg:1
      # PackageType: Image
      Architectures:
        - x86_64
      Tags:
        system: line-slideshow
      # Events:
      #   SQS:
      #     Type: SQS
      #     Properties:
      #       BatchSize: 1
      #       Queue: !Ref LineSlideshowSqsArn
      Environment:
        Variables:
          ENV: !Ref Env
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/make-slideshow-lambda-role-dev
      # Role: !Ref MakeSlideshowRoleArn
      # ImageUri: 935428647279.dkr.ecr.ap-northeast-1.amazonaws.com/make-lideshow:latest
    # Metadata:
    #   Dockerfile: Dockerfile
    #   DockerContext: main/
    #   DockerTag: python3.11
