AWSTemplateFormatVersion: "2010-09-09"

Description: dynamodb for line-slideshow

Parameters:
  Env:
    Type: String

Resources:
  LineSlideshowDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub line-slideshow-dynamodb-${Env}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 5
      Tags:
        - Key: system
          Value: line-slideshow
      BillingMode: PROVISIONED
  LineSlideshowDynamoDbContestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub line-slideshow-dynamodb-contest-${Env}
      AttributeDefinitions:
        - AttributeName: prize_id
          AttributeType: N
      KeySchema:
        - AttributeName: prize_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 5
      Tags:
        - Key: system
          Value: line-slideshow
      BillingMode: PROVISIONED
