AWSTemplateFormatVersion: "2010-09-09"

Description: Sqs for line-slideshow

Parameters:
  Env:
    Type: String

Resources:
  LineSlideshowSqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub line-slideshow-sqs-${Env}
      Tags:
        - Key: system
          Value: line-slideshow
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      SqsManagedSseEnabled: false
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt LineSlideshowDlQ.Arn
        maxReceiveCount: 1

  LineSlideshowDlQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub line-slideshow-dlq-${Env}
      Tags:
        - Key: system
          Value: line-slideshow
      VisibilityTimeout: 30
      MessageRetentionPeriod: 300
      SqsManagedSseEnabled: false
      RedriveAllowPolicy:
        redrivePermission: allowAll

  # LineSlideshowSqsPolicy:
  #   Type: AWS::SQS::QueuePolicy
  #   Properties:
  #     Queues:
  #       - !Ref LineSlideshowSqs
  # PolicyDocument:
  #   Statement:
  #     - Sid: 1
  #       Effect: Allow
  #       Principal: "*"
  #       Action: sqs:*
  #       Resource: !Ref LineSlideshowSqs
# arn:aws:iam::935428647279:role/apigw-calling-sqs-role-dev
# "Resource": "https://sqs.ap-northeast-1.amazonaws.com/935428647279/line-slideshow-sqs-dev.fifo"
