AWSTemplateFormatVersion: "2010-09-09"

Description: Sqs for line-slideshow

Parameters:
  Env:
    Type: String

Resources:
  LineSlideshowSqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub line-slideshow-sqs-${Env}.fifo
      Tags:
        - Key: system
          Value: line-slideshow
      FifoQueue: true
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 20
      SqsManagedSseEnabled: false

  LineSlideshowSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref LineSlideshowSqs
      PolicyDocument:
        Statement:
          - Sid: 1
            Effect: Allow
            Principal: "*"
            Action: sqs:*
            Resource: !Ref LineSlideshowSqs
