version = 0.1
[stg.deploy.parameters]
stack_name = "line-slideshow-backend"
resolve_s3 = true
s3_prefix = "line-slideshow-backend"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Env=\"stg\""
image_repositories = []
on_failure = "DO_NOTHING"

[prod.deploy.parameters]
stack_name = "line-slideshow-backend"
resolve_s3 = true
s3_prefix = "line-slideshow-backend"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Env=\"prod\""
image_repositories = []
