AWSTemplateFormatVersion: "2010-09-09"

Description: s3 for line-slideshow

Parameters:
  Env:
    Type: String

Resources:
  LineSlideshowS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub line-slideshow-s3-${Env}
      Tags:
        - Key: system
          Value: line-slideshow
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  LineSlideshowS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LineSlideshowS3Bucket
      PolicyDocument:
        Version: "2008-10-17"
        Id: "PolicyForCloudFrontPrivateContent"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::line-slideshow-s3-${Env}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::935428647279:distribution/E32NSO3QHFXN2M"
  LineSideshowCodeS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub line-slideshow-code-s3-${Env}
      Tags:
        - Key: system
          Value: line-slideshow
  LineSlideshowOpenBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub line-slideshow-open-s3-${Env}
      Tags:
        - Key: system
          Value: line-slideshow
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  LineSlideshowOpenBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LineSlideshowOpenBucket
      PolicyDocument:
        Version: "2008-10-17"
        Id: "PolicyForCloudFrontPrivateContent"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::line-slideshow-open-s3-${Env}/video/*"
